---

- name: install > Stat bin
  stat:
    path: "{{ manala_vault_cli_bin }}"
  register: __manala_vault_cli_bin_stat_result

- name: install > Get latest version
  uri:
    url: https://www.vaultproject.io/downloads
    return_content: true
  register: __manala_vault_cli_version_latest
  when: (not __manala_vault_cli_bin_stat_result.stat.exists)
        and (manala_vault_cli_version is none)

- set_fact:
    manala_vault_cli_version: "{{ __manala_vault_cli_version_latest.content|regex_search('(Current Version:.*)(\\d\\.\\d\\.\\d)')|regex_replace('(.*)(\\d\\.\\d\\.\\d)', '\\2') }}"
  when: (not __manala_vault_cli_bin_stat_result.stat.exists)
        and (manala_vault_cli_version is none)

- name: install > Install
  unarchive:
    src: "https://releases.hashicorp.com/vault/{{ manala_vault_cli_version }}/vault_{{ manala_vault_cli_version }}_linux_amd64.zip"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: true
  when: (not __manala_vault_cli_bin_stat_result.stat.exists)
